apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
  name: my-kubernetes-component
spec:
  lifecycle: dev
  owner: user:guest
  type: service
